# Generated by Django 5.1.2 on 2024-11-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="my_blog",
            name="publication_sign",
            field=models.BooleanField(default=True, verbose_name="Признак публикации"),
        ),
    ]
