# Generated by Django 5.1.2 on 2024-11-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_blog", "0002_my_blog_publication_sign"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="my_blog",
            options={"verbose_name": "Статья", "verbose_name_plural": "Статьи"},
        ),
        migrations.AddField(
            model_name="my_blog",
            name="number_of_views",
            field=models.PositiveIntegerField(
                default=0, verbose_name="колличество просмотров"
            ),
        ),
    ]
