# Generated by Django 5.1.2 on 2024-10-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=9, verbose_name="цена за покупку"
            ),
        ),
    ]
