# Generated by Django 5.1.2 on 2024-11-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to="media/photos/", verbose_name="фотография"
            ),
        ),
    ]
