# Generated by Django 5.1.2 on 2024-11-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="descriptions_category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_product",
            field=models.CharField(max_length=100, verbose_name="описание"),
        ),
    ]
